{% set name = "Flask-JSON" %}
{% set pname = "flask_json" %}
{% set version = "0.4.0" %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07945d66024f3b77694ce1db5d1fe83940f2aa3bcad8a608535686be67e4bc48

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - flask >=0.10

test:
  imports:
    - flask_json

about:
  license_family: BSD
  license: BSD-3-Clause
  home: https://github.com/skozlovf/flask-json
  license_file: LICENSE
  summary: Flask-JSON is a Flask extension providing better JSON support

  description: |
    Flask-JSON is a simple extension that adds better JSON support to Flask application
  doc_url: http://flask-json.readthedocs.io
  dev_url: https://github.com/skozlovf/flask-json

extra:
  recipe-maintainers:
    - knaaptime
